# Generated by Django 5.1.5 on 2025-03-10 00:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Όνομα')),
                ('last_name', models.CharField(max_length=50, verbose_name='Επώνυμο')),
                ('address', models.TextField(verbose_name='Διεύθυνση Διαμονής')),
                ('country', models.CharField(max_length=50, verbose_name='Χώρα')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Ταχυδρομικός Κώδικας')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Τηλέφωνο')),
                ('degree_title', models.CharField(max_length=100, verbose_name='Τίτλος Σπουδών')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
            ],
        ),
        migrations.CreateModel(
            name='T_C_Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='T_C', max_length=1000)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
    ]
