# Generated by Django 5.1.5 on 2025-03-10 00:23

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(blank=True, editable=False, max_length=1000, null=True)),
                ('ref_code', models.CharField(blank=True, editable=False, max_length=1000, null=True)),
                ('ref_code_book', models.CharField(blank=True, editable=False, max_length=1000, null=True)),
                ('stage', models.TextField(choices=[('primary', 'Δημοτικό'), ('secondary', 'Γυμνάσιο'), ('high', 'Λύκειο')], default='primary', max_length=300)),
                ('level', models.TextField(choices=[('first', 'Πρώτη'), ('second', 'Δεύτερα'), ('thirth', 'Τρίτη'), ('fourth', 'Τετάρτη'), ('fifth', 'Πέμπτη'), ('sixth', 'Έκτη')], default='first', max_length=300)),
                ('topic', models.TextField(choices=[('greek', 'Ελληνικά'), ('math', 'Μαθηματικά'), ('biology', 'Βιολογία'), ('physics', 'Φυσική'), ('chistry', 'Χημεία'), ('pliroforiki', 'Πληροφορική'), ('grammar', 'Γραμματική'), ('drastiriotites', 'Δραστηριότητες')], default='greek', max_length=300)),
                ('book_issue', models.CharField(choices=[('first_issue', 'Πρώτο Τεύχος'), ('second_issue', 'Δεύτερο Τεύχος'), ('thirth_issue', 'Τρίτο Τεύχος'), ('fourth_issue', 'Τέταρτο Τεύχος'), ('fifth_issue', 'Πέμπτο Τεύχος'), ('sixth_issue', 'Έκτο Τεύχος')], default='first_issue', max_length=500)),
                ('book_type', models.CharField(choices=[('mathiti', 'Βιβλίο Μαθητή'), ('ergasion', 'Βιβλίο Εργασιών'), ('grammar', 'Γραμματική'), ('drastiriotiton', 'Δραστηριοτήτων')], default='mathiti', max_length=500)),
                ('book_made_in', models.CharField(choices=[('gr', 'Ελληνικό'), ('cy', 'Κυπριακό')], default='gr', max_length=100)),
                ('book_title', models.CharField(max_length=500)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('book', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Books Images',
                'ordering': ['-sort'],
            },
        ),
        migrations.CreateModel(
            name='Image_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Image',
            },
        ),
        migrations.CreateModel(
            name='Image_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Login Image',
            },
        ),
        migrations.CreateModel(
            name='Image_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'News Image',
            },
        ),
        migrations.CreateModel(
            name='Image_primaryschool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Primary School Image',
            },
        ),
        migrations.CreateModel(
            name='Image_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Register Image',
            },
        ),
        migrations.CreateModel(
            name='Image_t_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Terms & Conditions Image',
            },
        ),
        migrations.CreateModel(
            name='Mylogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('mylogo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'My logo',
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Partnership',
            },
        ),
        migrations.CreateModel(
            name='Price_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code_video', models.CharField(blank=True, editable=False, max_length=1000, null=True)),
                ('stage', models.TextField(choices=[('primary', 'Δημοτικό'), ('secondary', 'Γυμνάσιο'), ('high', 'Λύκειο')], default='primary', max_length=300)),
                ('level', models.TextField(choices=[('first', 'Πρώτη'), ('second', 'Δεύτερα'), ('thirth', 'Τρίτη'), ('fourth', 'Τετάρτη'), ('fifth', 'Πέμπτη'), ('sixth', 'Έκτη')], default='first', max_length=300)),
                ('topic', models.TextField(choices=[('greek', 'Ελληνικά'), ('math', 'Μαθηματικά'), ('biology', 'Βιολογία'), ('physics', 'Φυσική'), ('chistry', 'Χημεία'), ('pliroforiki', 'Πληροφορική')], default='greek', max_length=300)),
                ('book_issue', models.CharField(choices=[('first_issue', 'Πρώτο Τεύχος'), ('second_issue', 'Δεύτερο Τεύχος'), ('thirth_issue', 'Τρίτο Τεύχος'), ('fourth_issue', 'Τέταρτο Τεύχος'), ('fifth_issue', 'Πέμπτο Τεύχος')], default='first_issue', max_length=500)),
                ('book_type', models.CharField(choices=[('mathiti', 'Βιβλίο Μαθητή'), ('ergasion', 'Βιβλίο Εργασιών')], default='mathiti', max_length=500)),
                ('book_made_in', models.CharField(choices=[('gr', 'Ελληνικο'), ('cy', 'Κυπριακό')], default='gr', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('price_chapter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_all_book', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Price_list',
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='Success_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, editable=False, max_length=1000, null=True)),
                ('Success_logo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Success_logo',
            },
        ),
        migrations.CreateModel(
            name='Terms_and_Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='T_C', max_length=1000)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, editable=False, max_length=1000, null=True)),
                ('ref_code_video', models.CharField(blank=True, editable=False, max_length=1000, null=True)),
                ('stage', models.CharField(choices=[('primary', 'Δημοτικό'), ('secondary', 'Γυμνάσιο'), ('high', 'Λύκειο')], default='primary', max_length=20)),
                ('level', models.CharField(choices=[('first', 'Πρώτη'), ('second', 'Δεύτερα'), ('thirth', 'Τρίτη'), ('fourth', 'Τετάρτη'), ('fifth', 'Πέμπτη'), ('sixth', 'Έκτη')], default='first', max_length=20)),
                ('topic', models.TextField(choices=[('greek', 'Ελληνικά'), ('math', 'Μαθηματικά'), ('biology', 'Βιολογία'), ('physics', 'Φυσική'), ('chistry', 'Χημεία'), ('pliroforiki', 'Πληροφορική')], default='greek', max_length=300)),
                ('book_issue', models.CharField(choices=[('first_issue', 'Πρώτο Τεύχος'), ('second_issue', 'Δεύτερο Τεύχος'), ('thirth_issue', 'Τρίτο Τεύχος'), ('fourth_issue', 'Τέταρτο Τεύχος'), ('fifth_issue', 'Πέμπτο Τεύχος')], default='first_issue', max_length=500)),
                ('book_type', models.CharField(choices=[('mathiti', 'Βιβλίο Μαθητή'), ('ergasion', 'Βιβλίο Εργασιών')], default='mathiti', max_length=500)),
                ('book_made_in', models.CharField(choices=[('gr', 'Ελληνικό'), ('cy', 'Κυπριακό')], default='gr', max_length=100)),
                ('part_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('chapter_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('part_video', models.TextField(choices=[(' ', 'Ένα Video'), ('- 1o Μέρος', 'Πρώτο Μέρος'), ('- 2o Μέρος', 'Δεύτερο Μέρος'), ('- 3o Μέρος', 'Τρίτο Μέρος'), ('- 4o Μέρος', 'Τέταρτο Μέρος'), ('- 5o Μέρος', 'Πέμπτο Μέρος'), ('- 6o Μέρος', 'Έκτο Μέρος'), ('- 7o Μέρος', 'Έβδομο Μέρος'), ('- 8o Μέρος', 'Όγδοο Μέρος'), ('- 9o Μέρος', 'Ένατο Μέρος')], default=' ', max_length=1000)),
                ('sorting_video', models.IntegerField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=1000, null=True)),
                ('what_includes', models.TextField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['stage', 'chapter_title', 'sorting_video'],
            },
        ),
        migrations.CreateModel(
            name='add_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos_url', models.CharField(blank=True, max_length=500, null=True)),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('part', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='')),
                ('book_title', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='display_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.TextField(blank=True, max_length=1000, null=True)),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('part', models.CharField(blank=True, max_length=500, null=True)),
                ('watch', models.BooleanField(default=False)),
                ('display_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(default='0:00:00', max_length=8)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='my_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos_url', models.CharField(blank=True, max_length=500, null=True)),
                ('book_title', models.TextField(blank=True, max_length=1000, null=True)),
                ('chapter', models.CharField(blank=True, max_length=500, null=True)),
                ('part', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
